name: Website

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mise tools (zola)
        uses: jdx/mise-action@v2

      - name: Build site
        run: zola build
